export type AppErrorCode =
  | "VALIDATION_ERROR"
  | "JSON_PARSE_ERROR"
  | "INVALID_CURSOR"
  | "SESSION_BUSY"
  | "SESSION_NOT_FOUND"
  | "UNAUTHORIZED_INTERNAL_ACCESS"
  | "TOOL_TIMEOUT"
  | "TOOL_EXECUTION_ERROR"
  | "MODEL_PROVIDER_ERROR"
  | "INTERNAL_SERVER_ERROR";

export const HTTP_STATUS_BY_CODE: Record<AppErrorCode, number> = {
  VALIDATION_ERROR: 422,
  JSON_PARSE_ERROR: 400,
  INVALID_CURSOR: 400,
  SESSION_BUSY: 409,
  SESSION_NOT_FOUND: 404,
  UNAUTHORIZED_INTERNAL_ACCESS: 401,
  TOOL_TIMEOUT: 504,
  TOOL_EXECUTION_ERROR: 502,
  MODEL_PROVIDER_ERROR: 502,
  INTERNAL_SERVER_ERROR: 500
};
